ALTER TYPE "LeadStage" RENAME VALUE 'NEW' TO 'Nouveau';
ALTER TYPE "LeadStage" RENAME VALUE 'CONTACTED' TO 'Contacte';
ALTER TYPE "LeadStage" RENAME VALUE 'QUALIFIED' TO 'Qualifie';
ALTER TYPE "LeadStage" RENAME VALUE 'PROPOSAL' TO 'Proposition';
ALTER TYPE "LeadStage" RENAME VALUE 'WON' TO 'Gagne';
ALTER TYPE "LeadStage" RENAME VALUE 'LOST' TO 'Perdu';
